[package]
name = "waveview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
fastwave_backend = {path = "FastWaveBackend"}
iced = {version = "0.6.0", features=["canvas"]}
iced_lazy = {version = "0.3.0"}
iced_native = {version = "0.3.0"}
camino = "1.1.1"
num = "0.4"
