[package]
name = "waveview"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug=true

[dependencies]
fastwave_backend = {path = "FastWaveBackend"}
iced = {version = "0.6.0", features=["canvas", "tokio", "debug"]}
iced_lazy = {version = "0.3.0"}
camino = "1.1.1"
num = "0.4"
pyo3 = {version = "0.17.3", features = ["auto-initialize"]}
color-eyre = "0.6.2"
