[package]
name = "surfer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[profile.release]
debug=true

[profile.dev]
opt-level=3

[dependencies]
fastwave_backend = {path = "FastWaveBackend"}
eframe = "0.20.1"
camino = "1.1.1"
num = "0.4"
color-eyre = "0.6.2"
clap = {version = "4.0.32", features=['derive']}
fern = { version = "0.6.1", features = ["colored"] }
log = "0.4"
progress-streams = "1.1.0"
itertools = "0.10.5"
serde = "1.0"
serde_stacker = "0.1"
spade = {path = "spade/spade-compiler"}
spade-common = {path = "spade/spade-common"}
spade-types = {path = "spade/spade-types"}
spade-mir = {path = "spade/spade-mir"}
spade-hir-lowering = {path = "spade/spade-hir-lowering"}
vcd-translate = {path = "spade/vcd-translate"}
ron = { version = "0.8.1", features = ["integer128"] }
fzcmd = {path = "fzcmd"}
