# Gruvbox light theme
[theme]
foreground = "3c3836"
background1 = { background = "fbf1c7", foreground = "3c3836" }
background2 = { background = "ebdbb2", foreground = "282828" }
background3 = { background = "d5c4a1", foreground = "282828" }
accent_info = { background = "076678", foreground = "7c6f64" }
accent_warn = { background = "d79921", foreground = "282828" }
accent_error = { background = "cc241d", foreground = "928c74" }
signal_default = "98971a"
signal_undefined = "cc241d"
signal_highimp = "d79921"
cursor = { color = "a0a0a0", width = 4 }
linewidth = 1

[theme.colors]
Green = "98971a"
Red = "cc241d"
Yellow = "d79921"
Blue = "458588"
Purple = "b16286"
Aqua = "689d6a"
Gray = "7c6f64"
Black = "282828"
