# Surfer zenburn
[theme]
foreground = "dcdccc"
background1 = { background = "3f3f3f", foreground = "dcdccc" }
background2 = { background = "2b2b2b", foreground = "dcdccc" }
background3 = { background = "4f4f4f", foreground = "dcdccc" }
accent_info = { background = "7f9f7f", foreground = "dcdccc" }
accent_warn = { background = "dfaf8f", foreground = "dcdccc" }
accent_error = { background = "cc9393", foreground = "dcdccc" }
signal_default = "7f9f7f"
signal_undefined = "cc9393"
signal_highimp = "f0dfaf"
cursor = { color = "a0a0a0", width = 4 }
linewidth = 1

[theme.colors]
Green = "7f9f7f"
Red = "cc9393"
Yellow = "f0dfaf"
Blue = "8cd0d3"
Magenta = "dc8cc3"
Cyan = "93e0e3"
Orange = "dfaf8f"
Gray = "989890"
